FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS build

RUN apk update && apk upgrade && \
  apk add --no-cache bash git openssh nodejs npm

WORKDIR /app

COPY *.sln .
COPY src/. ./src/

WORKDIR /app/src/Web.Identity

RUN dotnet restore

RUN npm install

RUN npm run lint-fix

RUN npm run production

RUN dotnet publish -c Release ./Web.Identity.csproj --no-restore -r linux-musl-x64 -o ./publish

FROM mcr.microsoft.com/dotnet/core/runtime-deps:3.0-alpine as runtime

EXPOSE 80

WORKDIR /app

COPY --from=build /app/src/Web.Identity/publish ./

ENTRYPOINT ["dotnet", "Web.Identity"]
