FROM nginx:alpine

RUN apk update && apk add --no-cache bash git openssh

RUN git clone -b staging https://github.com/RicardoGaefke/profile4d.git ./app

COPY ./app/nginx/default.cloud.conf ./etc/nginx/conf.d/default.conf
