FROM nginx:alpine

# RUN rm /usr/share/nginx/html/index.html
# RUN rm /etc/nginx/conf.d/default.conf
# RUN rm /etc/nginx/nginx.conf

# WORKDIR /usr/share/nginx/html

# COPY nginx/index.html .

# COPY nginx/default.dev.conf ./etc/nginx/nginx.conf

# WORKDIR /etc/nginx/conf.d/

COPY nginx/default.dev.conf ./etc/nginx/conf.d/default.conf


# FROM nginx:alpine

# WORKDIR /

# RUN rm /etc/nginx/conf.d/default.conf

# COPY ./nginx/default.dev.conf /etc/nginx/conf.d/default.conf

# WORKDIR /etc/nginx/conf.d/

# RUN ls

# RUN echo default.conf