version: '3'
networks:
  my-network:
    driver: bridge
services:
  web_api:
    image: ricardogaefke/profile4d:web_api_cloud
    container_name: web-api
    env_file:
      - ./docker-compose.env
    networks:
      - my-network
  nginx:
    image: ricardogaefke/profile4d:mynginx_cloud
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    networks:
      - my-network
