FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS build

RUN apk update && apk add --no-cache bash git openssh nodejs npm

WORKDIR /app

COPY *.sln .
COPY src/. ./src/

WORKDIR /app/src/Web.Site

RUN NODE_OPTIONS=--max_old_space_size=32768‬

RUN npm install

RUN npm run lint-fix

RUN npm run production

RUN dotnet publish -c Release ./Web.Site.csproj -r linux-musl-x64 -o ./publish

FROM mcr.microsoft.com/dotnet/core/runtime:3.0-alpine as runtime

RUN apk update && apk add --no-cache nodejs npm nodejs-npm

# RUN env PATH="/usr/bin/nodejs:/usr/bin/node:${PATH}"

# RUN echo $PATH

WORKDIR /app

COPY --from=build /app/src/Web.Site/publish ./

ENTRYPOINT ["./Web.Site"]
