FROM alpine as build

RUN apk update && apk add --no-cache bash git openssh

COPY ./nginx/default.cloud.conf ./app/default.cloud.conf
COPY ./nginx/localhost.crt ./app/localhost.crt
COPY ./nginx/localhost.rsa ./app/localhost.rsa

FROM nginx:alpine as publish

WORKDIR /app

COPY --from=build /app/default.cloud.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/localhost.crt /etc/ssl/certs/localhost.crt
COPY --from=build /app/localhost.rsa /etc/ssl/private/localhost.rsa
