FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS build

RUN apk update && apk add --no-cache bash git openssh nodejs npm

WORKDIR /app

COPY *.sln .
COPY src/. ./src/

WORKDIR /app/src/Web.Identity

RUN NODE_OPTIONS=--max_old_space_size=32768‬

RUN npm install

RUN npm run lint-fix

RUN npm run production

RUN dotnet publish -c Release ./Web.Identity.csproj -r linux-musl-x64 -o ./publish

FROM mcr.microsoft.com/dotnet/core/runtime:3.0-alpine as runtime

RUN apk update && apk add --no-cache nodejs npm nodejs-npm

RUN export PATH=$PATH:/usr/bin/node:/usr/share/doc/nodejs

ENV ASPNETCORE_URLS=http://+:5000

WORKDIR /app

COPY --from=build /app/src/Web.Identity/publish ./

ENTRYPOINT ["./Web.Identity"]

# docker build -f .\Dockerfile.web.identity.dev -t web_identity_dev --no-cache .
# docker create web_identity_dev
# docker run -it -t -p 8000:5000 web_identity_dev
# /usr/bin/node /usr/share/doc/nodejs
