FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine as build

RUN apk update && apk upgrade && apk add --no-cache bash openssh

WORKDIR /app

COPY *.sln .
COPY src/. ./src/

WORKDIR /app/src/WebJob.Teste

RUN dotnet publish -c Release ./WebJob.Teste.csproj -r linux-musl-x64 -o out

FROM mcr.microsoft.com/dotnet/core/runtime-deps:3.0-alpine as runtime

WORKDIR /app

COPY --from=build /app/src/WebJob.Teste/out ./

ENTRYPOINT ["./WebJob.Teste"]

# docker build -f .\Dockerfile.webjob.teste.cloud -t webjob_teste_cloud .
# docker create webjob_teste_cloud
# docker run -it --rm webjob_teste_cloud
#
# docker rmi $(docker images -a -q)
