export interface ILanguage {
  title: string,
  titlePT: {
    title: string,
    text: string,
    required: string,
    min: string,
    max: string,
  },
  titleENG: {
    title: string,
    text: string,
    required: string,
    min: string,
    max: string,
  },
  textPT: {
    title: string,
    text: string,
    required: string,
    min: string,
    max: string,
  },
  textENG: {
    title: string,
    text: string,
    required: string,
    min: string,
    max: string,
  },
  button: {
    title: string,
    text: string,
  },
  category: {
    title: string,
    text: string,
    text1: string,
    text2: string,
    text3: string,
    text4: string,
    text5: string,
    text6: string,
    text7: string,
    text8: string,
    text9: string,
  },
  created: {
    name: string,
    date: string,
  },
  feedback: {
    success: string,
    failure: string,
  },
}
