export interface ILanguage {
  title: string,
  firstpage: string,
  competent: string,
  dominantwhoiam: string,
  dominantname: string,
  dominantstructure: string,
  sabotagemode: string,
  sabotagewhoiam: string,
  sabotagedominant: string,
  sabotagename: string,
  competentxsabotage: string,
  trinitybehavioralcompetent: string,
  internalpartners: string,
  inamepartnerone: string,
  ifourpowersone: string,
  inamepartnertwo: string,
  ifourpowerstwo: string,
  trinitybehavioralsabotage: string,
}
