export interface ILanguage {
  title: string,
  images: string,
  dynamic: string,
  introduction: string,
  personalanalyze: string,
  inferiormind: string,
  dominantprofile: string,
  dominantwhoiam: string,
  dominantstructure: string,
  sabotagemode: string,
  sabotagewhoiam: string,
  sabotagedominant: string,
  competentxsabotage: string,
  trinitybehavioralcompetent: string,
  internalpartners: string,
  trinitybehavioralsabotage: string,
  internalenemies: string,
  namesaboteurone: string,
  sfourpowersone: string,
  namesaboteurtwo: string,
  sfourpowerstwo: string,
  pdi: string,
  threeintelligencecenters: string,
  energyspikes: string,
  trinityspecifics: string,
  originalxadapted: string,
}
