// eslint-disable-next-line no-unused-vars
import { ILanguage } from './ILanguage';

export default {
  title: 'Fixed content',
  images: 'Images list',
  dynamic: 'Dynamic content',
  introduction: 'Introduction',
  personalanalyze: 'Personal Analyze',
  inferiormind: 'Inferior Mind',
  dominantprofile: 'Your Dominant Profile',
  competentmode: 'Competent Mode',
  dominantwhoiam: 'Who am I?',
  dominantstructure: 'The structure of your dominant profile',
  dominantresources: 'Dominant Profile Resources',
  fourpersonalpowers: 'The Four Forces of Personality',
  yourmotivations: 'Your Motivations',
  attentionfocus: 'Attention Focus',
  leaderdifferential: 'Your Differential as Leader',
  relationedvaluesdomprofile: 'Values ​​related to your Dominant Profile',
  competentemotional: 'Competent Emotional',
  communicatesmode: 'How it communicates',
  interactsrelationships: 'Mode that interacts in Relationships',
  sabotagedominant: 'Features of your dominant profile',
  sabotagemode: 'Saboteur Mode',
  sabotagewhoiam: 'Who am I (saboteur)?',
  synthesissaboteur: 'Summary of its main Saboteur',
  limitingmatrix: 'Limiting Matrix Belief',
  communicationdifficulty: 'Difficulty in Communication',
  difficultyrelationships: 'Difficulty in Relationships',
  fourlimitationpowers: 'The Four Limiting Forces',
  limitingattitudes: 'Limiting Attitudes',
  behavioraladdiction: 'Behavioral Addiction',
  emotionaladdiction: 'Emotional Addiction',
  mentaladdiction: 'Mental Addiction',
  defensemecanisms: 'Defense Mecanisms',
  neuroticcompulsion: 'Neurotic Compulsion',
  competentxsabotage: 'Competent mode vs. saboteur mode',
  trinitybehavioralcompetent: 'Behavioral triad - Competent mode',
  internalpartners: 'Internal Partners',
  difficultycomunnication: 'Difficulty in Comunnication',
  fourpersonalitypowers: 'The Four Forces of Personality',
  trinitybehavioralsabotage: 'Trinity Behavioral Saboteur',
  internalenemies: 'Internal Enemies',
  firstfourlimitateforces: 'The Four Limiting Forces',
  secondfourlimitateforces: 'The Four Limiting Forces',
  pdi: 'Individual Development Plan',
  threeintelligencecenters: 'Three Intelligence Centers',
  behavioralrespectiveenergies: 'Behavioral Profiles and their Respective Energies (title)',
  identifiedconflicts: 'Identified Conflicts',
  energyspikes: 'Behavioral Triad and Energy Spikes',
  homogeneousheterogeneous: 'Triad (customized: Homogeneous or Heterogeneous)',
  trinityspecifics: 'Trinity Specifics',
  originalxadapted: 'Original Triad X Adapted Triad',
  exerciseprofilemoviment: 'Exercise to check the Profile Movement',
  superiormind: 'Superior Mind (title)',
  healthyadult: 'Your best version - The healthy adult',
  synergeticmode: 'Synergetic Mode (Increasing Mindset - Empowered Resources)',
  domprofile: 'Dominant Profile',
  bigchallenge: 'Your Big Challenge',
  workkey: 'Your Key Task',
  idealpartner: 'Your Ideal Partner',
  behavioraldna: 'Synthesis of your Behavioral DNA',
  archetypeessence: 'Discovering your Archetype - Its Essence',
  essentialfeature: 'Essential Feature',
  characterformation: 'Character Formation',
  moment: 'Moment',
  existentialpain: 'Existential Pain',
  noteexistentialpain: 'Existential Pain Note',
  crystallizationpersonality: 'Crystallization of Personality',
  bodystructurefixed: 'Body Structure (fixed)',
  bodyshape: 'Body Shape',
  mainvirtueessence: 'Main virtue to develop to get in touch with the Essence',
  benefitsvirtueessence: 'Benefits you will get from getting in touch with Essence',
  twelvecharacteradultstrengths: 'Twelve Strengths of the Healthy Adult',
  twelvecompetencesapresentation: 'Presentation of the twelve Competencies',
  fourcompetentstages: 'The four stages of competence',
  observation: 'Observation',
  twelvecompetences: 'The Twelve Skills',
  excellentcompromise: 'Compromise to excellence',
  conflictsresolution: 'Conflict resolution',
  adaptability: 'Adaptability',
  proactivity: 'Proactivity',
  internationalrelationship: 'Interpersonal relationship',
  clientorientation: 'Customer orientation',
  peoplesdevelopment: 'Development people',
  negotiationpersuation: 'Negotiation / Persuasion',
  inovationcriativity: 'Innovation / Creativity',
  entrepreneurorientation: 'Results oriented (Entrepreneur)',
  strategicalplanning: 'Strategic planning',
  systemicalvision: 'Systemic view',
  energybyarea: 'Energy by area of ​​activity',
  lastpageresume: 'Summary (last page)',
  dominantprofilename: 'Name of Dominant Profile',
  internalparnerone: 'Internal Partner Name (first)',
  internalpartnertwo: 'Internal Partner Name (second)',
  nameidealpartner: 'Ideal partner name',
  behavioralresources: 'Behavioral Profile Resource',
  twelvecompetencestable: 'Table of twelve competencies',
} as ILanguage;
