// eslint-disable-next-line no-unused-vars
import { ILanguage } from './ILanguage';

export default {
  title: 'Fixed content',
  images: 'Images list',
  dynamic: 'Dynamic content',
  firstpage: 'First page',
  competent: 'Competent mind',
  dominantwhoiam: 'Competent Who am I?',
  dominantname: 'Dominant Profile Name',
  dominantstructure: 'Dominant Profile Structure',
  sabotagemode: 'Sabotage Mode',
  sabotagewhoiam: 'Sabotage Who I Am?',
  sabotagedominant: 'Sabotage Dominant',
  sabotagename: 'Sabotage Profile Name',
  competentxsabotage: 'Mode Competent versus Mode Sabotage',
  trinitybehavioralcompetent: 'Trinity Behavioral Competent',
  internalpartners: 'Internal Partners',
  inamepartnerone: 'Name of First Internal Partner',
  ifourpowersone: 'Internal Four Powers One',
  inamepartnertwo: 'Name of Second Internal Partner',
  ifourpowerstwo: 'Internal Four Powers Two',
  trinitybehavioralsabotage: 'Trinity Behavioral Sabotage',
  internalenemies: 'Internal Enemies',
  namesaboteurone: 'Name Saboteur One',
  sfourpowersone: 'Sabotage Four Powers One',
  namesaboteurtwo: 'Name Saboteur Two',
  sfourpowerstwo: 'Sabotage Four Powers Two',
  pdi: 'Individual Development Plan',
  threeintelligencecenters: 'Three Intelligence Centers',
  behavioursprofiles: 'Behaviours Profiles',
  identifiedconflicts: 'Identified Conflicts',
  energyspikes: 'Energy Spikes',
  columncharthreeprofiles: 'Column Chart Three Profiles',
  trinitypersonified: 'Trinity Personified',
} as ILanguage;
