// eslint-disable-next-line no-unused-vars
import { ILanguage } from './ILanguage';

export default {
  title: 'Conteúdo fixo',
  images: 'Lista de imagens',
  dynamic: 'Conteúdo dinâmico',
  // forms list
  firstpage: 'Introdução',
  competentmind: 'Análise pessoal',
  dominantwhoiam: 'Mente inferior',
  dominantname: 'Seu perfil dominante',
  dominantstructure: 'Modo competente',
  sabotagemode: 'Quem eu sou?',
  sabotagewhoiam: 'A estrutura do seu perfil dominante',
  sabotagedominant: 'Recursos do seu perfil dominante',
  sabotagename: 'As quatro forças da personalidade',
  competentxsabotage: 'Suas motivações',
  trinitybehavioralcompetent: ' Seu foco de atenção',
  internalpartners: 'Seu diferencial como líder',
  inamepartnerone: ' Valores relacionados ao seu perfil dominante',
  ifourpowersone: ' Competência Emocional',
  inamepartnertwo: ' Modo que se comunica',
  ifourpowerstwo: 'Modo que interage nos relacionamentos',
  trinitybehavioralsabotage: 'Seu Sabotador Dominante',
  internalenemies: 'Modo sabotador',
  namesaboteurone: 'Quem sou (sabotador)?',
  sfourpowersone: ' Síntese do seu principal sabotador',
  namesaboteurtwo: 'Crença matriz limitante',
  sfourpowerstwo: 'Dificuldade na comunicação',
  pdi: 'Dificuldade nos relacionamentos',
  threeintelligencecenters: 'As quatro forças limitadoras',
  behavioursprofiles: 'Atitudes limitantes',
  identifiedconflicts: 'Vício Comportamental',
  energyspikes: 'Vício Emocional',
  columncharthreeprofiles: 'Vício Mental',
  trinitypersonified: 'Mecanismo de defesa',
  trinityspecifics: 'Compulsão Neurótica',
  originalxadapted: ' Modo competente X modo sabotador',
  graphicimage: 'Tríade comportamental – Modo competente',
  personalizedtext: 'Parceiros internos',
  explainedtext: 'Dificuldade na comunicação',
  personalizedtable: 'As quatro forças da personalidade',
  defaulttext: 'Tríade comportamental – Modo sabotador',
} as ILanguage;
