// eslint-disable-next-line no-unused-vars
import { ILanguage } from './ILanguage';

export default {
  title: 'Fixed content',
  images: 'Images list',
  dynamic: 'Dynamic content',
  introduction: 'Introduction',
  personalanalyze: 'Personal Analyze',
  inferiormind: 'Inferior Mind',
  twomindways: 'Your mind can act in two ways',
  dominantprofile: 'Your Dominant Profile',
  competentmode: 'Competent Mode',
  dominantwhoiam: 'Who am I?',
  nameprofileone: 'Profile name',
  dominantstructure: 'The structure of your dominant profile',
  dominantresources: 'Dominant Profile Resources',
  fourpersonalpowers: 'The Four Forces of Personality',
  yourmotivations: 'Your Motivations',
  attentionfocus: 'Attention Focus',
  leaderdifferential: 'Your Differential as Leader',
  relationedvaluesdomprofile: 'Values ​​related to your Dominant Profile',
  competentemotional: 'Competent Emotional',
  communicatesmode: 'How it communicates',
  interactsrelationships: 'Mode that interacts in Relationships',
  sabotagedominant: 'Features of your dominant profile',
  sabotagemode: 'Saboteur Mode',
  sabotagewhoiam: 'Who am I (saboteur)?',
  nameprofiletwo: 'Profile name',
  synthesissaboteur: 'Synthesis of its main Saboteur',
  limitingmatrix: 'Limiting Matrix Belief',
  communicationdifficulty: 'Difficulty in Communication',
  difficultyrelationships: 'Difficulty in Relationships',
  fourlimitationpowers: 'The Four Limiting Forces',
  limitingattitudes: 'Limiting Attitudes',
  behavioraladdiction: 'Behavioral Addiction',
  emotionaladdiction: 'Emotional Addiction',
  mentaladdiction: 'Mental Addiction',
  defensemecanisms: 'Defense Mecanisms',
  neuroticcompulsion: 'Neurotic Compulsion',
  competentxsabotage: 'Competent mode vs. saboteur mode',
  competentmodeone: 'Competent Mode',
  saboteurmodeone: 'Saboteur Mode',
  doyousee: 'Can you see?',
  trinitybehavioralcompetent: 'Behavioral triad - Competent mode',
  internalpartners: 'Internal Partners',
  difficultycomunnication: 'Who Am I?',
  nameprofilethree: 'Profile name',
  fourpersonalitypowers: 'The Four Forces of Personality',
  newwhoami: 'Who Am I?',
  nameprofilefour: 'Profile name',
  firstfourlimitateforces: 'The Four Forces of Personality',
  trinitybehavioralsabotage: 'Who Am I?',
  internalenemies: 'Internal Enemies',
  internalenemyone: 'Who Am I?',
  saboteurnameone: 'Saboteur name',
  secondfourlimitateforces: 'The Four Limiting Forces',
  internalenemytwo: 'Who Am I?',
  saboteurnametwo: 'Saboteur name',
  limitationfourpowers: 'The Four Limiting Forces',
  pdi: 'Individual Development Plan',
  threeintelligencecenters: 'Intelligence centers and their respective energies',
  threecenterslegend: 'Graphic legend of the Three Intelligence Centers',
  behavioralrespectiveenergies: 'Behavioral Profiles and their Respective Energies (title)',
  attentionpoints: 'Attention Points',
  identifiedconflicts: 'Identified Conflicts',
  energyspikes: 'Behavioral Triad and Energy Spikes',
  triadbehaviorallegend: 'Graphic legend of the behavioral triad',
  homogeneousheterogeneous: 'Triad (customized: Homogeneous or Heterogeneous)',
  observationattention: 'Attention Observation',
  triadspecificsone: 'Specific characteristic of the Triad',
  originalxadapted: 'Original Triad X Adapted Triad',
  triadlegends: 'Graphic legend of the Triad',
  observationtriad: 'Observation on the Triad',
  correctflux: 'Is your flow correct?',
  emotionalfluxresult: 'Result of the analysis of your emotional flow',
  dominantprofileone: 'Dominant Profile',
  internalpartone: 'Internal Partners',
  internalparttwo: 'Internal Partner',
  idealgrowthpart: 'Ideal partner for your growth',
  exerciseprofilemoviment: 'Exercise to check the Profile Movement',
  yourbehavioraldna: 'Your behavioral DNA',
  superiormind: 'Superior Mind (title)',
  healthyadult: 'Your best version - The healthy adult',
  synergeticmode: 'Synergetic Mode (Increasing Mindset - Empowered Resources)',
  archetypeessence: 'Discovering your Archetype - Its Essence',
  essentialfeature: 'Essential Feature',
  domprofile: 'Dominant Profile',
  bigchallenge: 'Your Big Challenge',
  workkey: 'Your Key Task',
  idealpartner: 'Your Ideal Partner',
  characterformation: 'Formation of your Dominant Profile',
  moment: 'Moment',
  existentialpain: 'Existential Pain',
  noteexistentialpain: 'Existential Pain Note',
  crystallizationpersonality: 'Crystallization Process of Your Dominant Profile',
  bodystructurefixed: 'Body Structure (fixed)',
  bodyshape: 'Body Shape',
  bodycharacters: 'Body feature',
  mainvirtueessence: 'Main virtue to develop to get in touch with the Essence',
  benefitsvirtueessence: 'Benefits you will get from getting in touch with Essence',
  twelvecharacteradultstrengths: 'Twelve Strengths of the Healthy Adult',
  professionalanalyze: 'Title professional analyze',
  twelvecompetencesapresentation: 'Presentation of the twelve Competencies',
  threedimensions: 'Three-dimensional text',
  fourcompetentstages: 'The four stages of Competence',
  observation: 'Observation',
  twelvecompetences: 'The Twelve Competences',
  excellentcompromise: 'Compromise to excellence',
  observationone: 'Observation 1',
  observationtwo: 'Observation 2',
  conflictsresolution: 'Conflicts resolution',
  observationthree: 'Observation 1',
  observationfour: 'Observation 2',
  adaptability: 'Adaptability',
  observationfive: 'Observation 1',
  observationsix: 'Observation 2',
  proactivity: 'Proactivity',
  observationseven: 'Observation 1',
  observationeight: 'Observation 2',
  internationalrelationship: 'Interpersonal relationship',
  observationnine: 'Observation 1',
  observationten: 'Observation 2',
  clientorientation: 'Customer orientation',
  observationeleven: 'Observation 1',
  observationtwelve: 'Observation 2',
  peoplesdevelopment: 'Development people',
  observationthirteen: 'Observation 1',
  observationfourteen: 'Observation 2',
  negotiationpersuation: 'Negotiation / Persuasion',
  observationfifteen: 'Observation 1',
  observationsixteen: 'Observation 2',
  inovationcriativity: 'Innovation / Creativity',
  observationseventeen: 'Observation 1',
  observationeighteen: 'Observation 2',
  entrepreneurorientation: 'Results oriented (Entrepreneur)',
  observationnineteen: 'Observation 1',
  observationtwenty: 'Observation 2',
  strategicalplanning: 'Strategic Planning',
  observationtwentyone: 'Observation 1',
  observationtwentytwo: 'Observation 2',
  systemicalvision: 'Systemic View',
  observationtwentythree: 'Observation 1',
  observationtwentyfour: 'Observation 2',
  energybyarea: 'Energy by area of ​​activity',
  graphiclegends: 'Graphic legend',
  inovationcriativityone: 'Innovation and creativity',
  managment: 'Planning',
  relationshipone: 'Relationship',
  controlexec: 'Execution and control',
  lastpageresume: 'Summary (last page)',
  dominantprofilename: 'Name of Dominant Profile',
  internalpartthree: 'Internal partners',
  internalpartnerone: 'Internal Partner Name (first)',
  internalpartnertwo: 'Internal Partner Name (second)',
  nameidealpartner: 'Ideal Partner Name',
  behavioralresources: 'Behavioral Profile Resource',
  competentresume: 'Skills Summary',
  competentlegends: 'Caption skills',
  // twelvecompetencestable: 'Table of twelve Competences',
  //  dynamic content
  questions: 'Questions',
} as ILanguage;
