// eslint-disable-next-line no-unused-vars
import { ILanguage } from './ILanguage';

export default {
  title: 'Conteúdo fixo',
  images: 'Lista de imagens',
  dynamic: 'Conteúdo dinâmico',
  introduction: 'Introdução',
  personalanalyze: 'Análise Pessoal',
  inferiormind: 'Mente Inferior',
  twomindways: 'Sua mente pode atuar de dois modos',
  dominantprofile: 'Seu Perfil Dominante',
  competentmode: 'Modo Competente',
  dominantwhoiam: 'Quem eu sou?',
  nameprofileone: 'Nome do perfil',
  dominantstructure: 'A estrutura do Perfil Dominante',
  dominantresources: 'Os recursos do Perfil Dominante',
  fourpersonalpowers: 'As Quatro Forças da Personalidade',
  yourmotivations: 'Suas Motivações',
  attentionfocus: 'Seu Foco de Atenção',
  leaderdifferential: 'Seu Diferencial como Líder',
  relationedvaluesdomprofile: 'Valores relacionados ao seu Perfil Dominante',
  competentemotional: 'Competência Emocional',
  communicatesmode: 'Modo que se comunica',
  interactsrelationships: 'Modo que interage nos Relacionamentos',
  sabotagedominant: 'Seu Sabotador Dominante',
  sabotagemode: 'Modo sabotador',
  sabotagewhoiam: 'Quem eu sou (sabotador)?',
  nameprofiletwo: 'Nome do perfil',
  synthesissaboteur: 'Síntese do seu principal Sabotador',
  limitingmatrix: 'Crença na Matriz Limitante',
  communicationdifficulty: 'Dificuldade na Comunicação',
  difficultyrelationships: 'Dificuldade nos Relacionamentos',
  fourlimitationpowers: 'As Quatro Forças Limitadoras',
  limitingattitudes: 'Atitudes Limitantes',
  behavioraladdiction: 'Vício Comportamental',
  emotionaladdiction: 'Vício Emocional',
  mentaladdiction: 'Vício Mental',
  defensemecanisms: 'Mecanismos de Defesa',
  neuroticcompulsion: 'Compulsão Neurótica',
  competentxsabotage: 'Modo Competente X Modo Sabotador',
  competentmodeone: 'Modo Competente',
  saboteurmodeone: 'Modo Sabotador',
  doyousee: 'Você consegue perceber?',
  trinitybehavioralcompetent: 'Tríade comportamental - Modo competente',
  internalpartners: 'Parceiros Internos',
  difficultycomunnication: 'Quem eu sou?',
  nameprofilethree: 'Nome do perfil',
  fourpersonalitypowers: 'As Quatro Forças da Personalidade',
  newwhoami: 'Quem eu sou?',
  nameprofilefour: 'Nome do perfil',
  firstfourlimitateforces: 'As Quatro Forças da Personalidade',
  trinitybehavioralsabotage: 'Tríade comportamental - Modo sabotador',
  internalenemies: 'Inimigos Internos',
  internalenemyone: 'Quem eu sou?',
  saboteurnameone: 'Nome do sabotador',
  secondfourlimitateforces: 'As Quatro Forças Limitadoras',
  internalenemytwo: 'Quem eu sou?',
  saboteurnametwo: 'Nome do sabotador',
  limitationfourpowers: 'As quatro forças limitadoras',
  pdi: 'Plano de Desenvolvimento Individual',
  threeintelligencecenters: 'Os centros de inteligência e suas respectivas energias',
  threecenterslegend: 'Legenda gráfico dos Três centros de Inteligência',
  behavioralrespectiveenergies: 'Perfis Comportamentais e suas Respectivas Energias',
  attentionpoints: 'Pontos de atenção',
  identifiedconflicts: 'Conflitos Identificados',
  energyspikes: 'Tríade Comportamental e os Picos de Energia',
  triadbehaviorallegend: 'Legenda gráfico da Tríade comportamental',
  homogeneousheterogeneous: 'Tríade (personalizada: Homogênea ou Heterogênea)',
  observationattention: 'Atenção Observação',
  triadspecificsone: 'Característica específica da Tríade',
  originalxadapted: 'Tríade Original X Tríade Adaptada',
  triadlegends: 'Legenda gráfico da Tríade',
  observationtriad: 'Observação sobre a Tríade',
  correctflux: 'Será que seu fluxo está correto?',
  emotionalfluxresult: 'Resultado da análise do seu fluxo emocional',
  dominantprofileone: 'Perfil Dominante',
  internalpartone: 'Parceiros internos',
  internalparttwo: 'Parceiro interno',
  idealgrowthpart: 'Parceiro ideal para seu crescimento',
  exerciseprofilemoviment: 'Exercício para verificar o Movimento do Perfil',
  yourbehavioraldna: 'Seu DNA comportamental',
  superiormind: 'Mente Superior',
  healthyadult: 'Sua melhor versão - O adulto saudável',
  synergeticmode: 'Modo sinérgico (aumento da mentalidade - recursos fortalecidos)',
  archetypeessence: 'Descobrindo seu Arquétipo – Sua Essência',
  essentialfeature: 'Característica Essencial',
  domprofile: 'Perfil Dominante',
  bigchallenge: 'Seu Grande Desafio',
  workkey: 'Sua Tarefa Chave',
  idealpartner: 'Seu Parceiro Ideal',
  characterformation: 'Formação do seu Perfil Dominante',
  moment: 'Momento',
  existentialpain: 'Dor Existencial',
  noteexistentialpain: 'Nota da Dor Existencial',
  crystallizationpersonality: 'Processo de Cristalização do seu Perfil Dominante',
  bodystructurefixed: 'Estrutura Corporal (fixo)',
  bodyshape: 'Formato do Corpo',
  bodycharacters: 'Característica do corpo',
  mainvirtueessence: 'Principal virtude a desenvolver para entrar em contato com a Essência',
  benefitsvirtueessence: 'Benefícios que terá ao entrar em contato com Essência',
  twelvecharacteradultstrengths: 'Doze Forças do caráter do Adulto Saudável',
  professionalanalyze: 'Análise profissional',
  twelvecompetencesapresentation: 'Apresentação das Doze Competências',
  threedimensions: 'Texto três dimensões',
  fourcompetentstages: 'Os quatro estágios da Competência',
  observation: 'Duas observações importantes',
  twelvecompetences: 'As Doze Competências',
  excellentcompromise: 'Compromisso com a excelência',
  observationone: 'Observação 1',
  observationtwo: 'Observação 2',
  conflictsresolution: 'Resolução de conflitos',
  observationthree: 'Observação 1',
  observationfour: 'Observação 2',
  adaptability: 'Adaptabilidade',
  observationfive: 'Observação 1',
  observationsix: 'Observação 2',
  proactivity: 'Proatividade',
  observationseven: 'Observação 1',
  observationeight: 'Observação 2',
  internationalrelationship: 'Relacionamento interpessoal',
  observationnine: 'Observação 1',
  observationten: 'Observação 2',
  clientorientation: 'Orientação para o cliente',
  observationeleven: 'Observação 1',
  observationtwelve: 'Observação 2',
  peoplesdevelopment: 'Desenvolvimento de pessoas',
  observationthirteen: 'Observação 1',
  observationfourteen: 'Observação 2',
  negotiationpersuation: 'Negociação / Persuasão',
  observationfifteen: 'Observação 1',
  observationsixteen: 'Observação 2',
  inovationcriativity: 'Inovação / Criatividade',
  observationseventeen: 'Observação 1',
  observationeighteen: 'Observação 2',
  entrepreneurorientation: 'Orientação para resultados (Empreendedor)',
  observationnineteen: 'Observação 1',
  observationtwenty: 'Observação 2',
  strategicalplanning: 'Planejamento Estratégico',
  observationtwentyone: 'Observação 1',
  observationtwentytwo: 'Observação 2',
  systemicalvision: 'Visão Sistêmica',
  observationtwentythree: 'Observação 1',
  observationtwentyfour: 'Observação 2',
  energybyarea: 'Energia por área de atuação',
  graphiclegends: 'Legenda gráfico',
  inovationcriativityone: 'Inovação e criatividade',
  managment: 'Planejamento',
  relationshipone: 'Relacionamento',
  controlexec: 'Execução e controle',
  lastpageresume: 'Resumo (última página)',
  dominantprofilename: 'Nome do Perfil Dominante',
  internalpartthree: 'Parceiros internos',
  internalpartnerone: 'Nome do Parceiro Interno (primeiro)',
  internalpartnertwo: 'Nome do Parceiro Interno (segundo)',
  nameidealpartner: 'Nome do Parceiro Ideal',
  behavioralresources: 'Recursos do Perfil Comportamental',
  competentresume: 'Resumo competências',
  competentlegends: 'Legenda competências',
  // twelvecompetencestable: 'Tabela das Doze Competências',
  //  dynamic content
  questions: 'Perguntas',
  profileName: 'Nome do perfil',
  featuresDominant: 'Recursos do seu perfil dominante',
  personalityForces: 'As quatro forças da personalidade',
  yourMotivations: 'Tuas motivações',
  focusAttention: 'Seu foco de atenção',
  leaderDifferent: 'Seu diferencial como líder',
  valuesDom: 'Valores relacionados ao seu perfil dominante',
  emotionalCompetence: 'Competência Emocional',
  comunicateMode: 'Modo que se comunica',
  interactMode: 'Modo que interage nos relacionamentos',
  profileNames: 'Nome do perfil',
  saboteurSynteshis: 'Síntese do seu principal sabotador',
  limitedMatrix: 'Crença matriz limitante',
  difficultComunicate: 'Dificuldade na comunicação',
  relationshipDifficult: 'Dificuldade nos relacionamentos',
  fourLimited: 'As quatro forças limitadoras',
  behavioralAddiction: 'Vício comportamental',
  emotionalAddiction: 'Vício emocional',
  mentalAddiction: 'Vício mental',
} as ILanguage;
